### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources.

### ISSUE THREAD

**Issue by Universalerror** [playgameservices/play-games-plugin-for-unity#1165]
After updating to revision 30 of Google Play Services I have began getting the aforementioned error when trying to build for Unity. Using Unity version 5.3.4f1. Possible culprit for the error is the Chartboost advertising plugin which seemed to at least partially depend on Google Play Services. I have attempted to upgrade the plugin by following the instructions provided in the txt file in the repository. Error log is as follows:

```
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Android\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Android\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.outlinegames.unibill.amazon:android.support.v7.appcompat:com.chartboost.sdk.unity:com.outlinegames.unibill.googleplay:com.google.firebase:com.outlinegames.googleplay:com.google.example.games.mainlibproj:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:com.google.android.gms.tasks:android.support.v4 -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\AmazonAppStore\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\common\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\firebase-common-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\GooglePlay\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-ads-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-ads-lite-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-base-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-basement-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-drive-8.4.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-games-8.4.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-nearby-8.4.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-plus-8.4.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\play-services-tasks-9.0.0\res" -S "C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/abc_alert_dialog_button_bar_material for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/abc_alert_dialog_material for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/abc_dialog_title_material for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.Truskill.CatchGT:layout/abc_screen_toolbar for configuration v21.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/abc_search_view for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_big_media for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_big_media_narrow for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_lines for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_media for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_part_chronometer for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/notification_template_part_time for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/select_dialog_multichoice_material for configuration v17.
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\Admin\Desktop\CatchGT\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.Truskill.CatchGT:layout/select_dialog_singlechoice_material for configuration v17.
AndroidManifest.xml:34: Tag <provider> attribute authorities has invalid character '$'.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Android\platforms\android-23\android.jar
applyFileOverlay for drawable
trying overlaySet Key=ic_plusone_medium_off_client.png
trying overlaySet Key=ic_plusone_small_off_client.png
trying overlaySet Key=ic_plusone_standard_off_client.png
trying overlaySet Key=ic_plusone_tall_off_client.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=ic_launcher.png
trying overlaySet Key=abc_ab_share_pack_mtrl_alpha.9.png
trying overlaySet Key=abc_action_bar_item_background_material.xml
trying overlaySet Key=abc_btn_borderless_material.xml
trying overlaySet Key=abc_btn_check_material.xml
trying overlaySet Key=abc_btn_check_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_check_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_colored_material.xml
trying overlaySet Key=abc_btn_default_mtrl_shape.xml
trying overlaySet Key=abc_btn_radio_material.xml
trying overlaySet Key=abc_btn_radio_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_radio_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_rating_star_off_mtrl_alpha.png
trying overlay<message truncated>
```

**Comment by mtman** [comment]
same issue

**Comment by claywilkinson** [comment]
Which version of the Plugin are you using?  This problem with the $ character has been resolved in a recent version of the plugin

**Comment by Universalerror** [comment]
I am using the most recent version of the plugin which at time of writing is version 0.9.33.

**Comment by Universalerror** [comment]
**Bump**
This issue is still persisting and is being very problematic, preventing the release of our product.

**Comment by claywilkinson** [comment]
Can you share the contents of your Assets/Plugins/Android directory?  I tried again this morning (with a new version of the plugin, but I don't think it should matter) and everything worked OK.

**Comment by Universalerror** [comment]
The contents of the Assets/Plugins/Android directory are as seen in this screenshot: 
![plugins1](https://cloud.githubusercontent.com/assets/15358716/15666651/ddecea50-2709-11e6-9eaf-710310e93d5d.png)

**Comment by Ankonian1** [comment]
I am having the same issue

**Comment by Nosbielc** [comment]
I am having the same issue

**Comment by claywilkinson** [comment]
@Nosbielc  - Can you open a new issue including the errors you are getting?  I doubt you are having the same issue as a year ago.  But if you are, try upgrading to the latest plugin version 0.9.39.
