### ISSUE TITLE
How to find out google_play_services_version

### ISSUE THREAD

**Issue by litemesa** [playgameservices/play-games-plugin-for-unity#1223]
Hi, I know this is an common problem, but I still cannot manage it.
First of all, after I add play-games-plugin-for-unity I start to get error
`AndroidManifest.xml:9: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')`
Then I have added Assets\Plugins\Android\res\values\version.xml to my project:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="google_play_services_version">4030500</integer>
</resources>`
After that building is ok, I call
`GooglePlayGames.PlayGamesPlatform.Activate();
Social.localUser.Authenticate(onProcessAuthentication); // error`
and in this case I get error, in log cat it looks like:
 `
Failure retrieving text 0x7f060006 in package com.lenovo.lenovohdllight
W/PackageManager(  876): android.content.res.Resources$NotFoundException: String resource ID #0x7f060006
W/PackageManager(  876):        at android.content.res.Resources.getText(Resources.java:303)
W/PackageManager(  876):        at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:1265)
W/PackageManager(  876):        at android.content.pm.ComponentInfo.loadLabel(ComponentInfo.java:85)
W/PackageManager(  876):        at android.content.pm.ResolveInfo.loadLabel(ResolveInfo.java:172)
W/PackageManager(  876):        at com.android.providers.applications.ApplicationsProvider.updateApplicationsList(ApplicationsProvider.java:566)
W/PackageManager(  876):        at com.android.providers.applications.ApplicationsProvider.access$400(ApplicationsProvider.java:72)
W/PackageManager(  876):        at com.android.providers.applications.ApplicationsProvider$UpdateHandler.handleMessage(ApplicationsProvider.java:227)
W/PackageManager(  876):        at android.os.Handler.dispatchMessage(Handler.java:110)
W/PackageManager(  876):        at android.os.Looper.loop(Looper.java:193)
W/PackageManager(  876):        at android.os.HandlerThread.run(HandlerThread.java:61)
I/PackageManager(  703): Adding preferred activity ComponentInfo{com.lenovo.ideafriend/com.lenovo.ideafriend.mms.android.ui.ComposeMessageActivity} for user 0 :
`
I think the problem is, I set incorrect google_play_services_version variable. I found many solutions in which people recommend find values.xml here: android-sdk/extras/google/google_play_services/libproject/google-play-services_lib/res/values/

But somehow I don't have this folder (I remember, I got it in previously, but not now), instead of it I have folder C:\Users\Eugene\AppData\Local\Android\android-sdk\extras\google\m2repository\com\google\android\gms\play-services - but I cannot find any integer value of service, only strings like 9.0.2.

So, could you please help find out, which google_play_services_version uses current unity plugin and what is the correspond integer version of it?

Unity 5.3.4
Google Play Services Rev. 30
Google Play Games Plugin for Unity 0.9.34

Thanks

**Comment by claywilkinson** [comment]
This value is in the Google play services client libraries.  Specifically, the plugin should add play-services-basement-9.0.x.aar to your Unity project in Assets/Plugins/Android.  You want to use the .aar files since including the entire client library (in google-play-services_lib) will make your APK unnecessarily large and may not even be able to be built due to the limit of 64k entries when converting to DEX.

**Comment by litemesa** [comment]
Thank you for quick response.
I have checked and found that plugin was added a play-services-basement-8.4.0 to Assets/Plugins/Android.
So, version of play service is 8.4.0, then I rename aar to zip and found a version.xml inside of it, and the integer version is 8487000 - bingo!
But, after I added this correct version.xml nothing is happened - the problem still persist.
At runtime I get this error:
`InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK

GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef)
GooglePlayGames.Native.NativeClient.InitializeGameServices ()
GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent)
GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent)
GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback)
GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback)
doodleRope.SocialDecorator.authenticate ()
doodleRope.DoodleRope.Start ()`

And in Unity Editor from time to time I get this: http://prntscr.com/bfyj1c
Maybe I need somehow to switch to the latest version, as you said play-services-basement-9.0.x.aar?

**Comment by claywilkinson** [comment]
Can you try the newer version of this plugin?  I think it fixes the editor exception you are seeing time to time.  This will also update the version requirement to 9+ to be more compatible with other plugins.

After updating the plugin, run Windows > Google Play Games > Setup > Android setup... again and paste the resources from the server into that dialog.

**Comment by litemesa** [comment]
If I download a ZIP current-build folder contains a GooglePlayGamesPlugin-0.9.34.unitypackage - same version I had integrated to my project, is it not the last one?

**Comment by litemesa** [comment]
If I try manually copy play-services-basement-9.0.1 instead of play-services-base-8.4.0 I get this alert:
http://prntscr.com/bg51oe

And if I choice OK plugin deletes version 9.0.1, and if I choice Keep it copies 8.4.0 (and, I think, continues to use it)

How could I tell plugin to use play-services-basement-9.0.1?

**Comment by claywilkinson** [comment]
This problem has been fixed in the latest version of the plugin: 0.9.36 - you can also turn off the background resolution in Assets/Play Services Resolver / Android Resolver / Settings.

**Comment by BruceHuang** [comment]
if you dont wan to use it , delete the  code <meta XXXXgoogle play XXX  /> in AndroidManifest.xml  which is added by AndroidStudio automatically,    then ->clean  -> rebuild

**Comment by pearl90** [comment]
I still face the same issue i have the latest plugin : 0.9.42 
and my error:
Gradle Error: Resource Not Found
Resource '@integer/google_play_services_version' not found in AndroidManifest.xml:31

**Comment by noorkaximi** [comment]
Facing the same problem have you got any solution

**Comment by pearl90** [comment]
Yes i have found a solution try this.
If you have GPGS plugin 0.9.42.
1. Go to GooglePlayGames/Plugin/Android/GooglePlayGamesManifest/
   open androidManifest.xml
  Cut the line: 
    
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
   and save.
2. Go to Assets/Plugins/Android/
    open androidManifest.xml (this is the main android manifest in the project if you don't have one create one there)
   and paste the following line you cut before inside the <application> tag. save and build!

Note: Its because grade is not reading this value thats why we are adding it in the main manifest.also make sure to completely remove it from the android manifest found in GPGS , don't worry the SDk will still work because in the end of the build all these androidManifest in the whole project will be added into one. Also always make sure when you do the 'android setup' in Windows/Google Play Games /setup/ Android setup , to go to the android manifest in GPGS and re-delete the line because the setup option will re-create the AndroidManifest and re-adds the line of code we deleted it.

At last Hopefully in the new release Google will fix this issue
