### ISSUE TITLE
Crash app android when starting  (Unity 2018.2.1f1 (64-bit) and Unity 2018.2.0f2 (64-bit)) GooglePlayGamesPlugin-0.9.50

### ISSUE THREAD

**Issue by Jbrandan** [playgameservices/play-games-plugin-for-unity#2254]
When I import the packate this error comes out (Solution #2013 did not work for me): 

```
Resolution failed

Failed to fetch the following dependencies:
com.android.support:support-annotations:25.2.0
com.android.support:support-compat:25.2.0
com.android.support:support-core-ui:25.2.0
com.android.support:support-core-utils:25.2.0
com.android.support:support-fragment:25.2.0
com.android.support:support-media-compat:25.2.0
com.android.support:support-v4:25.2.0
com.google.android.gms:play-services-auth-api-phone-license:11.6.2
com.google.android.gms:play-services-auth-api-phone:11.6.2
com.google.android.gms:play-services-auth-base-license:11.6.2
com.google.android.gms:play-services-auth-base:11.6.2
com.google.android.gms:play-services-auth:11.6.2
com.google.android.gms:play-services-base-license:11.6.2
com.google.android.gms:play-services-base:11.6.2
com.google.android.gms:play-services-basement-license:11.6.2
com.google.android.gms:play-services-basement:11.6.2
com.google.android.gms:play-services-drive-license:11.6.2
com.google.android.gms:play-services-drive:11.6.2
com.google.android.gms:play-services-games-license:11.6.2
com.google.android.gms:play-services-games:11.6.2
com.google.android.gms:play-services-nearby-license:11.6.2
com.google.android.gms:play-services-nearby:11.6.2
com.google.android.gms:play-services-tasks-license:11.6.2
com.google.android.gms:play-services-tasks:11.6.2
com.google.games:gpgs-plugin-support:0.9.50@srcaar


UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__26(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

**Comment by AurelioMV** [comment]
Same is happening with me on both Unity 2018.2.0 and 2018.2.1. Please fix it soon.

**Comment by Jbrandan** [comment]
I could solve it
1-Unity 2018.2.0f2 (64-bit) create scena with all your prefabs
2-delete project prefabs
3-copy the scene
4-Paste the scena in the old version of unity (Unity 2017.3.1f1 (64-bit))
5-re-create the prefabs with the objects in the scena stuck

**Comment by AurelioMV** [comment]
Thanks! That's a good temporary solution, but I switched to a 4K display after Unity started supporting IDE scaling in 2018.2 release. I'll remove the plugin for now and wait until Unity or Google comes up with a fix.

**Comment by Suvitruf** [comment]
This repo was updated last time 5 months ago. They don't event accept pull requests. So...

**Comment by AurelioMV** [comment]
Unity is currently the most used tool for creating android games, I don't think they will let Google Play Games Plugin not working...

**Comment by Suvitruf** [comment]
This plugin was developed by Google employee, not by Unity.

**Comment by rajeshdalsaniya** [comment]
@Jbrandan Try this it will work to solve dependency downloading issue which you facing - https://github.com/playgameservices/play-games-plugin-for-unity/issues/2243

**Comment by hsirkar** [comment]
Open `AndroidManifest.xml` found in `GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin` and replace all instances of "\ " (note the trailing space after the slash) with "\u003". Worked for me on 2018.2.1f1.

Creds [@khaledElshimy](https://www.github.com/khaledElshimy) from #2013

**Comment by gauravk95** [comment]
Try changing the build system from Gradle to Internal.

**Comment by exzizt** [comment]
Still an issue.

**Comment by wbsaputra** [comment]
Same here, crash when using social.auth, Unity 2018.2.0f2 (64-bit)) GooglePlayGamesPlugin-0.9.50
Anyone has solution?

**Comment by Grimicus** [comment]
One thing that happened for me is that the new google stuff seems to want a number instead of a string for com.google.android.gms.games.APP_ID but then it casts it to a number and fails to cast because of the beginning \ that the template puts into the file.   I changed it to add \0 to the end so it stays a string but since that is the null character it will parse correctly into an integer.  Another post I saw said you can add @string/ before the number and it should have the same effect.  This fixed the crash for me but I still have problems with authentication failing even though the UI shows up :(

**Comment by Jbrandan** [comment]
2018.2.1f1 already works in this version.
(Unity 2017.3.1f1 (64- bit))  but I'm still

**Comment by foenix76** [comment]
@hsirkar GPGS 9.5.0 + Unity 2018.2.6f 64bit(Win). You saved my life!! Thanks!!

**Comment by v01pe** [comment]
> Open `AndroidManifest.xml` found in `GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin` and replace all instances of "\ " (note the trailing space after the slash) with "\u003". Worked for me on 2018.2.1f1.
> 
> Creds [@khaledElshimy](https://www.github.com/khaledElshimy) from #2013

Wow, OK, nice hack! Still got other issues, but this is a bit progress!
Explanation of the hack, b/c i was curious: in unicode (that's what the `\u` stands for), all numbers start with \u003, so whatever comes afterwards is a number and thus is converted to unicode format…

I'm just curious why the failing `\ ` hack was needed in the first place and still isn't fixed.

**Comment by hypnos-dan** [comment]
> I'm just curious why the failing `\` hack was needed in the first place and still isn't fixed.

Google Play Services API changed.  It's parsing the value as an number and failing because of the space.   However, the project will fail to build if you don't force this field to be a string when it is built.   The unicode character seems to work for some reason idk which one it is but the number parsing doesn't fail.

I'm pretty sure no one at google is maintaining this anymore, which sucks because now we'll constantly be stumbling over whatever changes are made with no response from them.  Thanks everyone who is trying to keep this leaky ship afloat.

**Comment by HarrisonHough** [comment]
Also found another very similar solution that worked for me on this thread just FYI

You just remove the space after the "\" entirely. 

https://forum.unity.com/threads/unity-application-id-must-be-a-numeric-value-please-verify-that-your-manifest-refers-to-the-correct.544070/

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.51.

**Comment by code-doyen** [comment]
>           Should be fixed in 0.9.51.

0.9.51 does NOT fix, and \u003 can be omitted simply by removing the space between the backslash and app id like so "\APP_ID  
To fix, modify GooglePlayGames\Editor\template-AndroidManifest.txt and rerun Android setup

**Comment by synystro** [comment]
@hsirkar can't tell you how much I love you.
