### ISSUE TITLE
Unable to to load DLL 'gpg'

### ISSUE THREAD

**Issue by ephrisian** [playgameservices/play-games-plugin-for-unity#2294]
**Environment**
Unity: 2018.2.6f1
PlayGameServices: 0.9.50

Error: E/Unity: DllNotFoundException: Unable to load DLL 'gpg': The specified module could not be found.

**Build Settings**
Build System: Gradle, Internal (same for both)
Scripting Backend: IL2CPP, Mono (same for both)
Architecture: ARM64

Attempted solutions:
I was able to get the gpg libraries and fully functional Play Services with the 32-bit builds, however the application has already been uploaded as a 64-bit application and it is no longer an option to downgrade to 32-bit.

I have re-imported the plugin, downgraded to previous version, forced resolve, exported and built the project in Android Studio.

I have also changed the AndroidManifest template to have \u003 following previously suggested solutions.

**Comment by andyislay** [comment]
Hi Ephrisian

I have the same error.  Have not been able to resolve but this link seems to have a solution. https://github.com/playgameservices/play-games-plugin-for-unity/issues/280 although this was in 2014!

**Comment by OriginalsByToto** [comment]
Hi,

I have the same problem, the ARM64 arch is not supported now for GPG for Unity.
I tried the solution in the referenced issue, but I can't build the libgpg file because I can't find where are the files I need to modify.
Did this solve your problem?

**Comment by OriginalsByToto** [comment]
Yes, if I move to mono, it works, I think that this is the fact that ARM64 is not supported.
But the plugin really needs to be updated to work for ARM64 because this will be a requirement starting August 2019 and to my knowledge, no build instruction is given (I failed to follow the procedure explained in the referenced issue) : [https://blogs.unity3d.com/2017/12/20/meeting-google-play-requirements-in-the-future/](https://blogs.unity3d.com/2017/12/20/meeting-google-play-requirements-in-the-future/)

**Comment by andyislay** [comment]
Upgraded to 2018.2.11f1 - and seems to be working ok in IL2CPP. Signing into Google play ok.

**Comment by OriginalsByToto** [comment]
I can't test today, but I will try tomorrow this solution.
Very strange because I didn't see anything linked with this problem in the Unity changelog, even if there are changes about IL2CPP.

**Comment by OriginalsByToto** [comment]
I tried again and again, and the error is still there.
`DllNotFoundException: Unable to load DLL 'gpg': The specified module could not be found.`

I'm sure that ARM64 is causing the error because it's ok for ARMv7, and each time I tick or untick the ARM64 build support, the Android dependencies popup is shown and do some work in background.
Could something be done for this project? I am myself a little lost...

**Comment by andyislay** [comment]
The only other thing I can think I did was to reinstall the ndk r13b.  Although I don't seem to be getting the Android dependencies pop up anymore either.

Here are my player settings
![image](https://user-images.githubusercontent.com/7540425/47050553-bb281300-d198-11e8-94df-08119a3b4cd2.png)

**Comment by andyislay** [comment]
Also been getting the space in the AndroidManifest.  This link seems to provide a solution to that.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2013

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52.

**Comment by olehkuznetsov** [comment]
'Assets->Play Services Resolver->Android Resolver->Force Resolve' should help in this case.

**Comment by chwuchang** [comment]
Updated to 0.9.64 and this bug (Unable to to load DLL 'gpg') still exist.
Not working on: Il2Cpp-ARM64
Working on: Il2Cpp-ArmV7, Il2Cpp-x86, Mono-all

**Comment by OriginalsByToto** [comment]
I'm still on the 0.9.63 version.
I will make a backup and try to switch to the new version.
I will get back to see if it's working.

**Comment by OriginalsByToto** [comment]
Do you have a stacktrace to compare and try to see where is the problem?
Maybe it's linked with the updated Gradle version and the updated tools to compile the package...

**Comment by chwuchang** [comment]
![error](https://user-images.githubusercontent.com/8456353/57229497-d54c1480-7048-11e9-89d1-3ae75be5a33c.png)

**Comment by chwuchang** [comment]
@OriginalsByToto Have you fixed it?

**Comment by chwuchang** [comment]
![image](https://user-images.githubusercontent.com/8456353/57229953-d598df80-7049-11e9-8221-2e21d0c419da.png)

**Comment by OriginalsByToto** [comment]
I'm at school.
I will try in 1 hour approximately and get back here.

**Comment by OriginalsByToto** [comment]
I tried with the new version and there is no problem for me, the game is correctly loaded (except the user image that is loaded over HTTP).
That's strange...

I have no time to investigate today because of my lessons but I will search tomorrow.

**Comment by chwuchang** [comment]
Thanks for your help，my gradle tools version 3.2.0,unity3d version 2017.4.26

**Comment by OriginalsByToto** [comment]
@chwuchang I may have an idea on what's the problem, but can you create a new issue, exposing your problem and referencing this issue, because this one is already closed.

I think it will be better to talk on the new thread.
