### ISSUE TITLE
libgpg not included with arm64 

### ISSUE THREAD

**Issue by Baraphor** [playgameservices/play-games-plugin-for-unity#2327]
Hey,

I am trying to switch over to ILTOCPP for our Android builds, however I cannot because lipgpg.so is not included with arm64 builds.

**Comment by olehkuznetsov** [comment]
Which version of libgpg do you use? 

This one definitely contains 'arm64-v8a' lib folder:
https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v3.0.1.zip

**Comment by olehkuznetsov** [comment]
Can you try 0.9.51, please? It should be fixed there.

**Comment by Baraphor** [comment]
> Can you try 0.9.51, please? It should be fixed there.

Will do when able.

**Comment by Baraphor** [comment]
> Can you try 0.9.51, please? It should be fixed there.

Hey,

I can confirm that it is still not working, when I build the apk, there are three folders inside the lib folder, however libgpg.so is missing from the arm64-v8a folder, which causes the game to lockup on launch.

**Comment by dtorres-kabam** [comment]
I tested in a empty project here. It generated a com.google.games.gpgs-plugin-support-0.9.51.aar in the Plugins/Android folder. This .aar file does not contain the .so for armv8.

On the other hand, the gpgs-plugin-support-0.9.51.srcaar file contains .so for armv8. I am not sure how this whole GPG framework works, but if you replace the .aar by the .srcaar (keep the same .aar file name), it works (it worked for me).

The funny thing is that I did that yesterday. Yeah, I downloaded the whole repo, and compiled myself for armv8. Anyway, I am interested in the recommended way for upgrading this plugin.

**Comment by olehkuznetsov** [comment]
It seems it is enough to wipe file /Assets/Plugins/Android/com.google.games.gpgs-plugin-support-0.9.51.aar
And it would be replaced by correct one during resolve phase.

**Comment by olehkuznetsov** [comment]
It seems Force Resolve options in Play Services Resolver works too.

**Comment by Baraphor** [comment]
> It seems Force Resolve option in Play Services Resolver works too.

Didn't work for me, I had to manually replace the file.

**Comment by dtorres-kabam** [comment]
I downloaded the version 0.9.52 and imported to a new empty project, and the .aar file at Assets/Plugins/Android does NOT contain the .so for arm 64. Wiping the file does not fix it.

The trick to replace the .aar by the .srcaar is not a complete solution either. I tested making builds for armv7 only, and the app does not run. I get a "Failure to Initialize!", "Your hardware does not support this application, sorry?". I made the build with Unity 5.6.5.

**Comment by dtorres-kabam** [comment]
I wonder if this issue should be reopened. Is @olehkuznetsov listening to it?

**Comment by MigrantP** [comment]
We are also experiencing this issue, and Force Resolve does not fix it. Following Baraphor's steps worked, thanks!

**Comment by dtorres-kabam** [comment]
Just for future reference, here are some notes to help figuring out this whole thing. I am assuming that you have the correct version of the GPG (>= 0.9.52), and the Play Services Resolver run successfully.

Running the Play Services Resolver will work if you have the _Target Architecture_ properly set in the _PlayerSettings_ (that seems to be where the resolver gets the Architecture info from).  The resolver will unpack/unzip the .srcaar file, remove the .so files for the undesired architectures, repack it back into a .aar file, and place it in the plugins folder. The _Explode AARs_ option needs to selected in the resolver settings.

AFAIK, these are the steps when running the Play Services Resolver. Hope it helps.

**Comment by Firemaw** [comment]
Thanks @dtorres-kabam changing the Target Architecture to include 64-bit, then running the resolver worked for me.
