### ISSUE TITLE
Application.Quit () makes it unstable on Android

### ISSUE THREAD

**Issue by grayger** [playgameservices/play-games-plugin-for-unity#310]
When Application.Quit () is called on back key, the game finished normally.
But trying to execute the app again makes it crash after 5~10 seconds' waiting with black screen.

The log during the waiting is as below:
12-12 17:59:02.918: V/GamesNativeSDK(3686): Received Activity Stop Event.
12-12 17:59:02.958: V/GamesNativeSDK(3686): Attached to JVM on thread main_dispatch
12-12 17:59:02.958: V/GamesNativeSDK(3686): Running disconnect operation.
12-12 17:59:08.023: V/GamesNativeSDK(3686): Detaching from JVM on thread main_dispatch

and just after the crash, executing the app again is OK.

device: Galaxy Note 
plugin version: GooglePlayGamesPlugin-0.9.10
unity: 4.5.5f1 mac

Do you have any idea? 
Shouldn't I use Application.Quit() or is there any way to release GamesNativeSDK on quitting?

**Comment by GameDrill** [comment]
Did you removed previous plugin completely?

**Comment by vector-8** [comment]
Same problem here using this plug-in in combination with unityads http://unityads.unity3d.com  
Game takes 4-8 seconds to close and (sometimes) to load the next scene.

**Comment by blackrainbowgames** [comment]
Same problem. Sometimes ANR

**Comment by simsis3d** [comment]
I was having freezing(around 10-12 second) problem on application quit. Then a clever guy recommended a solution like removing PlayerProxyActivity from AndroidManifest file. Then I did it. Then my problem was transformed to your problem. Application freezes for around 5-6 second on application start. Described here https://github.com/playgameservices/play-games-plugin-for-unity/issues/370

**Comment by rdaros** [comment]
Ctrl-Z

**Comment by sayeed360** [comment]
Okay  0.9.07 definitely works . no issues at all

**Comment by blackrainbowgames** [comment]
@sayeed360 0.9.07 does not support SavedGames. For achievements and leaderboards - you can use it.

**Comment by andreiciceu** [comment]
I'm havint ghe same problem here... Please fix it guys

**Comment by blackrainbowgames** [comment]
Hi! Not fixed in 0.912 (((((((((((((((((((((((

**Comment by Gamya** [comment]
I think I found a workaround that seems to work: http://gamya-games.blogspot.com.es/2015/02/problems-with-google-play-plugin-for.html

**Comment by blackrainbowgames** [comment]
@Gamya Thanks! I wonder this issue is still not fixed around 2 month

**Comment by claywilkinson** [comment]
We're looking into it - stay tuned....

**Comment by ajnaduvil** [comment]
@Gamya : can u please give some idea how to create that simple android plugin in unity?

**Comment by Gamya** [comment]
I posted a reply in the comments section of the blog.

I think it's a bit confusing because it's difficult to explain with detail in a comment. I'm going to make a mini-tutorial, but for now you can check out that comment to see if it helps.

**Comment by ajnaduvil** [comment]
@Gamya : Thank  u so much  for the help. I have integrated it in a small game i made. It works for me well :)

**Comment by hippogamesunity** [comment]
@Gamya can you upload your plugin? Thanks!

**Comment by hippogamesunity** [comment]
Fixed in ver 15?

**Comment by IvyKun** [comment]
Still not fixed on 0.9.15...

Same as 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/424
and
https://github.com/playgameservices/play-games-plugin-for-unity/issues/398

**Comment by IvyKun** [comment]
Reading about @Gamya approach I ended up doing the same but without the plugin. It's not a solution, closing is not the same as moving to back, but well, it works as a workaround.

Just call this instead of Application.Quit.

private void CustomApplicationQuit() 
    {
         #if UNITY_ANDROID
            using (AndroidJavaClass javaClass = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
            {
                AndroidJavaObject unityActivity = javaClass.GetStatic<AndroidJavaObject>("currentActivity");
                unityActivity.Call<bool>("moveTaskToBack", true);
            }
        #else
            Application.Quit();
        #endif
    }

**Comment by Piflik** [comment]
Little correction to @IvyKun's last comment: I had to specify the type argument for 'GetStatic' and the return type for 'Call'. Other than that, this workaround works like a charm, at least at first glance.

private void CustomApplicationQuit() {
#if UNITY_ANDROID
    using (AndroidJavaClass javaClass = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) {
        AndroidJavaObject unityActivity = javaClass.GetStatic<AndroidJavaObject>("currentActivity");
        unityActivity.Call<bool>("moveTaskToBack", true);
    }
#else
    Application.Quit();
#endif
}

**Comment by ahsyarif008** [comment]
i cannot use the code @IvyKun  and @Piflik. there is something error on """"AndroidJavaObject unityActivity = javaClass.GetStatic("currentActivity"); """""
when i try to run game there is error log on it.

**Comment by Piflik** [comment]
@ahsyarif008 
Apparently this board ignores stuff between 'less than' and 'grater than' smbols in text that is not marked as code...hadn't even noticed that my code was missing the exact same stuff I had to add to @IvyKun's until now...

Anyway, i updated my last post, it should be working now.

**Comment by IvyKun** [comment]
Wow, thanks @Piflik because I didn't noticed either. My code is the same that the one in @Piflik  post. I'm using it right now in a few games and works good.

**Comment by szakill** [comment]
I haven't tested this to long but after upgrading Andrioid Support Library and Google Play services in Android SDK manager my application doesn't crash any more after quit.

**Comment by staythirsty90** [comment]
Hello,

I'm experiencing the issue as well. Using 0.9.20

**Comment by claywilkinson** [comment]
Looks like this had a Unity bug also.  According to their [Release Notes](http://unity3d.com/unity/whats-new/unity-5.0.2), this issue is fixed.

**Comment by staythirsty90** [comment]
Unfortunately the issue is still present, at least for me :(

**Comment by claywilkinson** [comment]
That is too bad.  Can you file a bug with Unity? http://issuetracker.unity3d.com/

**Comment by GameDrill** [comment]
The issue is not closed. It's close because of duplicate. The issue is
still opened.

**Comment by claywilkinson** [comment]
@GameDrill - I understand that Application.Quit() is causing problems.  Can you provide a log?  Since Unity is aware of the issue, I am skeptical that it is specific to this plugin.  If you think otherwise, please help me understand where you think the problem is and re-open the issue.

**Comment by GameDrill** [comment]
I am also finding the solution. For now I have downgraded the  Unity GPG
plugin version 0.9.02 which works. Also, there are lot of features pending
in UnityGPG. e.g. LoadScore function is just a placeholder. I think they
are waiting to someone else from community to contribute. It will be now
nearly 8-9 months this issue is pending.

**Comment by kyuskoj** [comment]
this issue is still present... I've wasted my time for 2 days..

**Comment by yanhuiinf** [comment]
I still meet the question now,Unity version is 5.4.3,gpg version is latest new .I used the method of "moveTaskToBack";

**Comment by ArmandCloud** [comment]
Same here. Unity 5.3.5 p1 + Plugin 0.9.34.
**//This is normal quit when i just silent sign in.**

05-29 15:42:38.140 32355-32355/com.guya.dragracingproclutch I/Unity: onPause
05-29 15:42:38.240 32355-458/com.guya.dragracingproclutch D/Unity: Setting up 1 worker threads for Enlighten.
05-29 15:42:38.240 32355-459/com.guya.dragracingproclutch D/Unity:   Thread -> id: 841b5ad0 -> priority: 1 
05-29 15:42:38.450 32355-32384/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcess:IL
05-29 15:42:38.450 32355-32384/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodGetInfo:II
05-29 15:42:38.450 32355-32384/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcessMicData:ILI
05-29 15:42:42.144 32355-32355/com.guya.dragracingproclutch W/Unity: Timeout while trying to pause the Unity Engine.
05-29 15:42:42.154 32355-32355/com.guya.dragracingproclutch I/Choreographer: Skipped 240 frames!  The application may be doing too much work on its main thread.
05-29 15:42:42.154 32355-32355/com.guya.dragracingproclutch I/Unity: windowFocusChanged: false
05-29 15:42:42.154 32355-32355/com.guya.dragracingproclutch V/GamesNativeSDK: Received Activity Stop Event.
05-29 15:42:42.164 32355-553/com.guya.dragracingproclutch V/GamesNativeSDK: Attached to JVM on thread main_dispatch
05-29 15:42:42.164 32355-553/com.guya.dragracingproclutch V/GamesNativeSDK: Running disconnect operation.
05-29 15:42:46.157 32355-32355/com.guya.dragracingproclutch I/Unity: onDestroy
05-29 15:42:46.167 32355-32355/com.guya.dragracingproclutch D/Unity: [EGL] Attaching window :0x0
05-29 15:42:46.177 32355-32355/com.guya.dragracingproclutch I/Process: Sending signal. PID: 32355 SIG: 9

**//This is CRASHED quit when i silent sign in + initialize nearby.**

05-29 15:45:49.917 749-749/com.guya.dragracingproclutch I/Unity: onPause
05-29 15:45:50.007 749-1502/com.guya.dragracingproclutch D/Unity: Setting up 1 worker threads for Enlighten.
05-29 15:45:50.017 749-1503/com.guya.dragracingproclutch D/Unity:   Thread -> id: 83ae0a10 -> priority: 1 
05-29 15:45:50.227 749-808/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcess:IL
05-29 15:45:50.227 749-808/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodGetInfo:II
05-29 15:45:50.227 749-808/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcessMicData:ILI
05-29 15:45:53.921 749-749/com.guya.dragracingproclutch W/Unity: Timeout while trying to pause the Unity Engine.
05-29 15:45:53.921 749-749/com.guya.dragracingproclutch I/Choreographer: Skipped 240 frames!  The application may be doing too much work on its main thread.
05-29 15:45:53.921 749-749/com.guya.dragracingproclutch I/Unity: windowFocusChanged: false
05-29 15:45:53.931 749-749/com.guya.dragracingproclutch V/GamesNativeSDK: Received Activity Stop Event.
05-29 15:45:53.931 749-749/com.guya.dragracingproclutch V/GamesNativeSDK: NearbyConnections client disconnected.
05-29 15:45:53.931 749-1629/com.guya.dragracingproclutch V/GamesNativeSDK: Attached to JVM on thread main_dispatch
05-29 15:45:53.931 749-1629/com.guya.dragracingproclutch V/GamesNativeSDK: Running disconnect operation.
05-29 15:45:53.931 749-808/com.guya.dragracingproclutch A/libc: Fatal signal 11 (SIGSEGV) at 0x83ebe9d8 (code=1), thread 808 (main)

**//This is normal quit of unity empty project**

05-29 15:47:15.260 1715-1715/com.asd.asd I/Unity: onPause
05-29 15:47:15.270 1715-2182/com.asd.asd D/Unity: Setting up 1 worker threads for Enlighten.
05-29 15:47:15.270 1715-2183/com.asd.asd D/Unity:   Thread -> id: 81adc5b0 -> priority: 1 
05-29 15:47:15.300 1715-1732/com.asd.asd D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcess:IL
05-29 15:47:15.300 1715-1732/com.asd.asd D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodGetInfo:II
05-29 15:47:15.300 1715-1732/com.asd.asd D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcessMicData:ILI
05-29 15:47:15.450 1715-1732/com.asd.asd D/Unity: Waiting for finish
05-29 15:47:15.500 1715-1732/com.asd.asd D/Unity: ASensorManager_destroyEventQueue returned 0
05-29 15:47:15.510 1715-1732/com.asd.asd I/Unity: ##unity-automation:{"messageType":"MemoryLeaks","allocatedMemory":18947,"memoryLabels":[{"NewDelete":18172},{"Manager":72},{"String":131},{"ScriptManager":496},{"SceneManager":76}]}
05-29 15:47:15.560 1715-1715/com.asd.asd I/Unity: windowFocusChanged: false
05-29 15:47:15.720 1715-1715/com.asd.asd D/Unity: [EGL] Attaching window :0x0
05-29 15:47:16.181 1715-1732/com.asd.asd D/v_gal: [tid=1732] TLS is not valid if _TLSDestructor is called before.
05-29 15:47:16.181 1715-1715/com.asd.asd I/Unity: onDestroy
05-29 15:47:16.201 1715-1715/com.asd.asd I/Process: Sending signal. PID: 1715 SIG: 9

**Some how GamesNativeSDK doing some job when unity call onPause.**

Regards,

**Comment by leonard4** [comment]
Seeing this behavior now on 10.0.1, was not getting this on 9.8.0 and earlier.

**Comment by AnilThapliyal08** [comment]
Can use :

System.Diagnostics.Process.GetCurrentProcess().Kill();
// instead of
//Application.Quit();

**Comment by DoofahSoftware** [comment]
> Can use :
> 
> System.Diagnostics.Process.GetCurrentProcess().Kill();
> // instead of
> //Application.Quit();

This fixed the timeout messages for me.
