### ISSUE TITLE
Some conflicting dependencies were found. error

### ISSUE THREAD

**Issue by random0v0** [playgameservices/play-games-plugin-for-unity#3137]
![제목 없음](https://user-images.githubusercontent.com/96767622/161499622-f84e1bfa-778c-4d0d-b030-cc7467183fdf.png)

I'm use Unity 2020.3.30f1 version, and i try import GPGS 0.11.01 version but i have some error. what should i do?

**Comment by akirayui** [comment]
Is there any progress on this issue?

**Comment by random0v0** [comment]
> Is there any progress on this issue?
I fixed it! In 2020.3.30f1 version, GPGS v0.10.12 version will Work.

**Comment by akirayui** [comment]
The problem persist with these setups:

Unity 2020.3.20f1
Play Games Plugin v11.01
Google Mobile Ads 7.0.0

Unity 2020.3.33f1
Play Games Plugin v11.01
Google Mobile Ads 7.0.0

If I use Play Games v0.10.1, it conflicts with Google Mobile Ads again.

**Comment by BlackCatKPI** [comment]
Spent a lot of time resolving this issue. And succeded.

Here the resolution:

> Used proguard file
> Minify in debug and release
> Force resolve. 

And it worked.

**Comment by tomurtogu** [comment]
> Spent a lot of time resolving this issue. And succeded.
> 
> Here the resolution:
> 
> > Use proguard file
> > Minify in debug and release
> > Force resolve.
> 
> And it worked.

I've already done these steps. In my case, I found that the problem was in the fb mediation adapter.
I added plugins to an empty project one by one, and after every import, I run "force resolve dependencies". There was no such warning until I imported the facebook mediation adapter, so I think the problem is related to the facebook mediaton adapter.

**Comment by BlackCatKPI** [comment]
Also the pass to inner repository (GooglePlayGamesPluginDependencies.xml) has to be checked:
in my case I changed repository in GooglePlayGamesPluginDependencies.xml to
        <repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>

**Comment by tomurtogu** [comment]
I didn't make any changes to the repo. It was already like you said. 
Maybe the version you use is older.

```
<?xml version="1.0" encoding="UTF-8"?>
<dependencies>
  <!-- Internal library dependency generated at build time. 
    It also defines the transitive dependencies on play-services
-->
  <androidPackages>
    <androidPackage spec="com.google.games:gpgs-plugin-support:0.11.01">
      <repositories>
        <repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```

**Comment by random0v0** [comment]
> Same warnings using Unity 2021.3.0f1 & Play Games Plugin v11.01
> 
> Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11: Repo path 'Packages/com.google.play.games/Editor/m2repository' does not exist.
> 
> Some conflicting dependencies were found. The following dependency versions were modified: com.google.games:gpgs-plugin-support:0.11.01 --> com.google.games:gpgs-plugin-support:+


try v10.14

**Comment by m0s-ivan** [comment]
> 

It was working without problems with the previous version (10.14).
I'm not planning to downgrade since I've already migrated to Play Games Services Sign In v2.

**Comment by kyubuns** [comment]
I am also getting the same error with the combination of Same warnings using Unity 2020.3 & Play Games Plugin v11.01.
Do I have to downgrade?
