### ISSUE TITLE
Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.games.PlayGames

### ISSUE THREAD

**Issue by EdgarGomez** [playgameservices/play-games-plugin-for-unity#3269]
**Describe the bug**
I've installed latest version of the plugin 0.11.01 and I´m getting this error when executing, once build, the login: Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.games.PlayGames

I'm getting the error by connecting my phone and using Android Logcat. Actually the full error is:

``

The code I'm using for now is this:
`using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;

public class GooglePlayServicesManager : MonoBehaviour
{
    public static GooglePlayServicesManager Instance { get; private set; }
    public bool isConnectedToGPS = false;
    private SignInStatus status;

    private string leaderBoardId = "xxxxxx";

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);

            // Initialize Google Play Services here if needed

            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();
        }
        else
        {
            Destroy(gameObject);
        }
    }

    public void Start()
    {
        PlayGamesPlatform.Instance.Authenticate(ProcessAuthentication);
    }

    public void LogIn()
    {
        PlayGamesPlatform.Instance.Authenticate(ProcessAuthentication);
    }

    internal void ProcessAuthentication(SignInStatus status)
    {
        if (status == SignInStatus.Success)
        {
            // Continue with Play Games Services
        }
        else
        {
            // Disable your integration with Play Games Services or show a login button
            // to ask users to sign-in. Clicking it should call
            // PlayGamesPlatform.Instance.ManuallyAuthenticate(ProcessAuthentication).
        }
    }

    public void ShowLeaderboard()
    {
        PlayGamesPlatform.Instance.ShowLeaderboardUI(leaderBoardId);
    }

    public void ShowAchievements()
    {
        PlayGamesPlatform.Instance.ShowAchievementsUI();
    }

    public void UnlockAchievement(string achievementID)
    {
        PlayGamesPlatform.Instance.ReportProgress(achievementID, 100.0f, (bool success) =>
        {
            if (success)
            {
                Debug.Log("Score reported successfully!");
            }
            else
            {
                Debug.LogError("Failed to report score.");
            }
        });
    }

    public void ReportScore(long score, string leaderboardID)
    {
        PlayGamesPlatform.Instance.ReportScore(score, leaderboardID, (bool success) =>
        {
            if (success)
            {
                Debug.Log("Score reported successfully!");
            }
            else
            {
                Debug.LogError("Failed to report score.");
            }
        });
    }

}
`

I´ve tried everything I've seen about this error and similar ones. [Custom Proguard file](https://github.com/playgameservices/play-games-plugin-for-unity/issues/3154#issuecomment-1129919620), [fixing the file android dependencies](https://github.com/playgameservices/play-games-plugin-for-unity/issues/3220#issuecomment-1609903080), [changing things inside the manifest](https://github.com/playgameservices/play-games-plugin-for-unity/issues/3154#issuecomment-1293257681), [using resolve and force resolve](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2796#issuecomment-575335598), checking debug and release in minification... but none of those are working for me. Also changed the Sha1 from my play console inside developers hub. I'm still getting the error and I don't know what else do or try.

Please help.

**Versions**
- Unity version: 2021.3.25f1
- Google Play Games Plugin for Unity version: 0.11.01

**Additional context**
It's a 2d game with 2d Core installed, Unity ads, another plugin for translations and nothing else. Shouldnt be a conflict with those.

**Comment by AndroidRub** [comment]
APKTodo - The beginning of Mod APK Technology
The source of the best Mod APK versions
Are you looking for the best Mod APK games and apps for Android, stop here, we will cover all your needs. At APKTodo we always create and bring to you, as well as everyone, full-featured s that help you open the game and own it as full gold without having to plow. You want to win? We will be the one to pave the way for you, bringing victory closer to you. APKTodo is a APK distributor with unexpected changes and differences - all our apps and games are always stable and legal on all platforms.

Thousands of free Mod APK games
With thousands of Mod APK games for you to explore, with the diversity of genres we are growing stronger and stronger towards a good future, meeting the entertainment needs for everyone. all around the world. I believe you can find anything you want here. We have everything for you, from action games, role playing, FPS shooting even racing or puzzle games - and many more.

You did not hear wrong, by downloading the APK you have never played before, get unlimited status and privileges right now at [APKTodo](https://apktodo.io/). Don't download from boring original stores or an unsafe provider come to us and you will not have to pay anything for interesting games.

Unlimited Premium Mod APK App
At APKTodo, you are provided not only with a variety of games, but also with premium applications that are completely free. Want to watch thousands of famous movies or blockbusters on Netflix APK without paying? It's very simple, just download our app, with premium features you will have the most perfect experience you have ever had.

We always provide a variety of useful applications to users around the world with advanced features, you can take photos, record movies, even edit images with our brand new features. Get rid of boring native apps, add to our app collection you'll have with the latest technology features today.

**Comment by EdgarGomez** [comment]
This is still happening. Any ideas?

**Comment by wtblife** [comment]
I'm also struggling with this same issue. None of the solutions I tried (the ones you listed) have worked.

**Comment by rami-al-rahim** [comment]
Hi I tried to change this line of code in GooglePlayGamesPluginDependencies.xml form this 
` <repository>Packages/com.google.play.games/Editor/m2repository</repository>`
to this
` <repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>`

**Comment by theeugeneL** [comment]
I'm using unity 2022.3.4f1 and GooglePlayGamesPlugin-0.11.01
Tried all of the above and nothing worked for me.

I fixed the issue by add this line of code in Plugins/Android/mainTemplate.gradle

```
dependencies {
    implementation "com.google.android.gms:play-services-games-v2:+"
  }
```

**Comment by ZhangHuan0407** [comment]
unity 2021.3.33, plugin 0.11.01
This is still happening.
Does anyone know what an Android project looks like when properly exported?
![image](https://github.com/playgameservices/play-games-plugin-for-unity/assets/60495057/c44867ef-5fc0-428b-99e2-d7d57c94b7d8)
this file: Assets/GooglePlayGames/com.google.play.games/Editor/m2repository/com/google/games/gpgs-plugin-support/0.11.01/gpgs-plugin-support-0.11.01.srcaar
if rename and unzip this file, open directory, rename and unzip classes.jar, you will find some class in folder classes - unzip\com\google\games\bridge
I don't know what is .srcaar file. But my gut tells me that this file should be exported to an Android project, or unzipped to an Android project.

**Comment by sameehj** [comment]
> I'm using unity 2022.3.4f1 and GooglePlayGamesPlugin-0.11.01 Tried all of the above and nothing worked for me.
> 
> I fixed the issue by add this line of code in Plugins/Android/mainTemplate.gradle
> 
> ```
> dependencies {
>     implementation "com.google.android.gms:play-services-games-v2:+"
>   }
> ```

This worked for me! Thank you SIR!

**Comment by longshilin** [comment]
Unity2022.3.17f1c1  Solved!!!  If you have other doubts about this issue, you can @ me here

![image](https://github.com/playgameservices/play-games-plugin-for-unity/assets/18352884/433fb51d-477e-4ef5-9b2a-f1ec9cb7b284)

![image](https://github.com/playgameservices/play-games-plugin-for-unity/assets/18352884/70701d76-1a2b-4beb-a107-c76660a1e2b1)


**mainTemplate.gradle**

```
apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation "com.google.android.gms:play-services-games-v2:+"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
**DEPS**}

android {
    ndkPath "**NDKPATH**"

    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

```

**gradleTemplate.properties**

```
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
unityStreamingAssets=**STREAMING_ASSETS**
android.useAndroidX=true
**ADDITIONAL_PROPERTIES**
```

**Comment by longshilin** [comment]
Ref: https://github.com/googlesamples/unity-jar-resolver/issues/208

**Comment by mattmisk** [comment]
> I'm using unity 2022.3.4f1 and GooglePlayGamesPlugin-0.11.01 Tried all of the above and nothing worked for me.
> 
> I fixed the issue by add this line of code in Plugins/Android/mainTemplate.gradle
> 
> ```
> dependencies {
>     implementation "com.google.android.gms:play-services-games-v2:+"
>   }
> ```

Thank you SO much!!!

**Comment by pang0018** [comment]
You can also disable minify in the Player settings in Android (if you don't care about minifying the Android code)

**Comment by ClemCa** [comment]
> ```
> dependencies {
>     implementation "com.google.android.gms:play-services-games-v2:+"
>   }
> ```
OMG thank you I spent hours researching this issue, both last week and today, and your solution solved the issue

**Comment by Hestiny** [comment]
I encountered this issue with Unity 2022.3.34 as well, and it was eventually resolved, though I'm not entirely sure which step made the difference. Here’s what I did as a reference:

1. Added the following in the AndroidManifest:

<meta-data android:name="com.google.android.play.billingclient.version" android:value="6.2.1" />

Removed the following from mainTemplate:

exclude group: 'com.android.billingclient', module: 'billing'

(Mainly because it caused a build error, so I did this to fix it. The error was as follows: The attribute meta-data#com.google.android.play.billingclient.version@value=6.0.1 in com.android.billingclient:billing:6.2.1 collides with another value).

2. Added -keep class com.android.billingclient.** {*; } to proguard-user.

3. Deleted the Library folder, then reopened the project and built it again.
