### ISSUE TITLE
Exception java.lang.NullPointerException: null reference at com.google.android.gms.games.ui.signinflow.SignInChimeraActivity.F 

### ISSUE THREAD

**Issue by tomurtogu** [playgameservices/play-games-plugin-for-unity#3306]
I see in the Google pre launch report that the crash occurs on Google Pixel 5, Motorola G20,  and Google Pixel 5 64 bit only devices. I have tried with all Unity LTS versions, with both API 33 and API 34 as target SDK. I have uploaded about 15 builds, the error does not go away. I also added the proguard file as instructed.

**Versions**
- Unity version: 2020.3.48f1, 2021.3.39f1, 2022.3.34f1
- Google Play Games Plugin for Unity version: 11.01

`Exception java.lang.NullPointerException: null reference
  at m.dlv.o (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):8)
  at com.google.android.gms.games.ui.signinflow.SignInChimeraActivity.F (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):14)
  at m.jer.az (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):5)
  at m.jch.f (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):42)
  at m.jch.b (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):3)
  at m.jer.aS (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):8)
  at m.jer.l (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):28)
  at m.dg.e (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):481)
  at m.cv.at (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):1144)
  at m.cv.av (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):83)
  at m.cv.am (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):71)
  at m.cg.run (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):4)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at m.nhj.dispatchMessage (:com.google.android.gms.optional_games@242013034@24.20.13 (100000-0):138)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)`

**Comment by tomurtogu** [comment]
no one?

**Comment by smile616** [comment]
The issue has been fixed in Google Mobile Services v24.22.

Based on the stack trace you have Google Mobile Services v24.20.13 on the device. Visit https://play.google.com/store/apps/details?id=com.google.android.gms on the device to install an update.

Please reopen if you can reproduce the issue with Google Mobile Services v24.22+.

**Comment by tomurtogu** [comment]
Thank you for your reply.
I don't actually see this issue on my own devices, but it shows up in the Google Play Console pre-launch reports, so I can't release any updates. Do you have any idea how I can pass the tests?

**Comment by smile616** [comment]
Ah, I see. Missed that it was about pre-launch reports.

Unfortunately I don't know any easy ways. My best bet would be to wait until the pre-launch would contains mostly v24.22+ devices. So try every other day? 

But google, maybe there is something else?

**Comment by smile616** [comment]
does it still have "24.20.13" in the stack trace?

**Comment by tomurtogu** [comment]
Yes, same stack trace.

**Comment by smile616** [comment]
I see

**Comment by tomurtogu** [comment]
There is another crash. The project is blank,  only includes the Google Play Games plugin. 
The problem seems to be related to GMS 24.20.13 again. 
Since I cannot update their devices, is there nothing to be done on your side?

`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3189)
  at android.os.Parcel.createException (Parcel.java:3167)
  at android.os.Parcel.readException (Parcel.java:3150)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:202)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:154)
  at android.content.ContentProviderProxy.call (ContentProviderNative.java:764)
  at android.content.ContentResolver.call (ContentResolver.java:2466)
  at android.content.ContentResolver.call (ContentResolver.java:2446)
  at ekfr.a (:com.google.android.gms@242013038@24.20.13 (190400-633713831):29)
  at com.google.android.gms.wallet.intentoperation.setupwizard.PaymentsSetupWizardAccountChangeIntentOperation.onHandleIntent (:com.google.android.gms@242013038@24.20.13 (190400-633713831):252)
  at com.google.android.chimera.IntentOperation.onHandleIntent (:com.google.android.gms@242013038@24.20.13 (190400-633713831):2)
  at ajdw.onHandleIntent (:com.google.android.gms@242013038@24.20.13 (190400-633713831):8)
  at pbh.run (:com.google.android.gms@242013038@24.20.13 (190400-633713831):70)
  at pbg.run (:com.google.android.gms@242013038@24.20.13 (190400-633713831):152)
  at elbx.run (:com.google.android.gms@242013038@24.20.13 (190400-633713831):21)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)`

**Comment by gpgames** [comment]
Google Pixel 8 device too.

**Comment by smile616** [comment]
> PaymentsSetupWizardAccountChangeIntentOperation

Suggests the issue is not related to the Google Play Games plugin.

**Comment by smile616** [comment]
@tomurtogu / @gpgames Could you try again in a couple of days, and report back?

It's expected that the `Exception java.lang.NullPointerException: null reference at ... com.google.android.gms.optional_games ... com.google.android.gms.games.ui.signinflow.SignInChimeraActivity` should disappear.

**Comment by thomaskiesl** [comment]
Same issue here
`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3189)
  at android.os.Parcel.createException (Parcel.java:3167)
  at android.os.Parcel.readException (Parcel.java:3150)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:202)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:154)
  at android.content.ContentProviderProxy.call (ContentProviderNative.java:764)
  at android.content.ContentResolver.call (ContentResolver.java:2466)
  at android.content.ContentResolver.call (ContentResolver.java:2446)
  at elwr.a (:com.google.android.gms@242335038@24.23.35 (190400-646585959):29)
  at com.google.android.gms.wallet.intentoperation.setupwizard.PaymentsSetupWizardAccountChangeIntentOperation.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):252)
  at com.google.android.chimera.IntentOperation.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):2)
  at ajom.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):8)
  at pkf.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):70)
  at pke.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):152)
  at emsz.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):21)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)`

**Comment by smile616** [comment]
> > PaymentsSetupWizardAccountChangeIntentOperation
> 
> Suggests the issue is not related to the Google Play Games plugin.

As per comment above: PaymentsSetupWizardAccountChangeIntentOperation is not related to the original issue. 

Anyway, I've checked and NullPointerException in PaymentsSetupWizardAccountChangeIntentOperation was fixed in gms v24.26. I'd expect by 2024-07-18 fix should reach most of the devices and pre launch should be unblocked.

@tomurtogu / @gpgames please report back

**Comment by mhctseu** [comment]
> > > PaymentsSetupWizardAccountChangeIntentOperation
> > 
> > 
> > Suggests the issue is not related to the Google Play Games plugin.
> 
> As per comment above: PaymentsSetupWizardAccountChangeIntentOperation is not related to the original issue.
> 
> Anyway, I've checked and NullPointerException in PaymentsSetupWizardAccountChangeIntentOperation was fixed in gms v24.26. I'd expect by 2024-07-18 fix should reach most of the devices and pre launch should be unblocked.
> 
> @tomurtogu / @gpgames please report back

This issue still exists in my google play pre-launch report on 2024-07-19:

`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3189)
  at android.os.Parcel.createException (Parcel.java:3167)
  at android.os.Parcel.readException (Parcel.java:3150)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:202)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:154)
  at android.content.ContentProviderProxy.call (ContentProviderNative.java:764)
  at android.content.ContentResolver.call (ContentResolver.java:2466)
  at android.content.ContentResolver.call (ContentResolver.java:2446)
  at elwr.a (:com.google.android.gms@242335038@24.23.35 (190400-646585959):29)
  at com.google.android.gms.wallet.intentoperation.setupwizard.PaymentsSetupWizardAccountChangeIntentOperation.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):252)
  at com.google.android.chimera.IntentOperation.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):2)
  at ajom.onHandleIntent (:com.google.android.gms@242335038@24.23.35 (190400-646585959):8)
  at pkf.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):70)
  at pke.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):152)
  at emsz.run (:com.google.android.gms@242335038@24.23.35 (190400-646585959):21)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)`
