### ISSUE TITLE
Support library has moved

### ISSUE THREAD

**Issue by LoungeKatt** [playgameservices/play-games-plugin-for-unity#331]
The GPGSAndroidSetupUI script attempts to find the support library at /extras/android/support/v4/android-support-v4.jar which is now located at extras/android/compatibility/v4/android-support-v4.jar

In addition, the iOS instructions attached to the Editor download option tell you to download the iOS file marked Games SDK Version xx.yy.zz when you actually need the C++ file marked Play Games C++ SDK Version xx.yy or you do not have the gpg.framework (as the popup properly details).

The Android manifest no longer includes a version code. The next best place for that is the version.xml
```
\\string libProjAM = libProjPath + GPGSUtil.SlashesToPlatformSeparator("/AndroidManifest.xml");
  string libProjAM = libProjPath + GPGSUtil.SlashesToPlatformSeparator("/res/values/version.xml");
```
but this also requires making some changes to CheckAndWarnAboutGmsCoreVersion which are a bit too "hacky" in my version, as all I needed was for it to work once.

**Comment by mrggl** [comment]
Thanks for the info, we'll address this in an upcoming release of the plugin.

**Comment by claywilkinson** [comment]
tracking internally as 18951620

**Comment by claywilkinson** [comment]
Fixed in Version 0.9.15.

**Comment by LoungeKatt** [comment]
As of 0.9.20, the "missing" support library issue still exists.

GooglePlayGames/Editor/GPSGUtil.cs contains

string supportJarPath = sdkPath +
                                    GPGSUtil.SlashesToPlatformSeparator(
                                        "/extras/android/support/v4/android-support-v4.jar");

which should be

string supportJarPath = sdkPath +
                                    GPGSUtil.SlashesToPlatformSeparator(
                                        "/extras/android/compatibility/v4/android-support-v4.jar");
