### ISSUE TITLE
ANR on app quit

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#398]
Hi! It takes about 10-20 seconds to quit app after plugin activation. I suppose it is stop bug, but it is not fixed since Dec14. Please provide info.
0.912, Sony Z1 and all tested devices.

**Comment by claywilkinson** [comment]
@hippogamesunity  - I believe this is the same issue as #310.  I believe we know what is going on, it is a bug in the games services for android.  A fix should be coming soon. Please stand by...

**Comment by hippogamesunity** [comment]
@claywilkinson Please provide link to this bug. Also was it fixed in ver 15?

**Comment by claywilkinson** [comment]
Looks like this had a Unity bug also.  According to their [Release Notes](http://unity3d.com/unity/whats-new/unity-5.0.2), this issue is fixed.

**Comment by simgesimulation** [comment]
Hey @claywilkinson. We are using Unity 5.1.1p4 and GPGS plugin 0.9.25, but problem is still alive. I think it is not on unity side. When we use GPGS 0.9.7, the problem goes away. Other threads about issue: https://github.com/playgameservices/play-games-plugin-for-unity/issues/310  https://github.com/playgameservices/play-games-plugin-for-unity/issues/370

**Comment by hippogamesunity** [comment]
@simgesimulation Hi, I have no problems now (Unity 4.6.8 + GPGS plugin 0.9.25). Try to use my android manifest maybe.

<?xml version="1.0" encoding="utf-8"?>
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	package="com.unity3d.player"
	android:installLocation="preferExternal"
	android:theme="@android:style/Theme.NoTitleBar"
	android:versionCode="1"
	android:versionName="1.0">
	
	<uses-permission android:name="com.android.vending.BILLING" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	
	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"
		android:anyDensity="true"/>

	<application
		android:icon="@drawable/app_icon"
		android:label="@string/app_name"
		android:debuggable="true">
		<activity android:name="com.unity3d.player.UnityPlayerNativeActivity"
			android:label="@string/app_name">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
				<category android:name="android.intent.category.LEANBACK_LAUNCHER" />
			</intent-filter>
			<meta-data android:name="unityplayer.UnityActivity" android:value="true" />
			<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
		</activity>
	</application>    
</manifest>

**Comment by claywilkinson** [comment]
@simgesimulation Thanks for the update.  If you can reproduce it, can you tell me the version of play services, play games (the app) and which version of the OS?  And a bugreport file  (once it happens, run adb bugreport and capture the output to a file.).

**Comment by claywilkinson** [comment]
Closed as dup of #370.
