### ISSUE TITLE
Wrong authentication callback status

### ISSUE THREAD

**Issue by readych** [playgameservices/play-games-plugin-for-unity#443]
Version information: Unity 5.0.0 & Play Game Plugin for Unity v0.9.15 & Google Play Service library 23 (7095000)

I found a strange issue with the callback method of the Authenticate method. (tested on Android 5.1)
`Social.localUser.Authenticate((bool success) => { });`
The callback method calls back with the status flag (variable `success`) "false" (instead of "true"), even though the login was successful.
Attention: This issue only happens if I do the following procedure:
1. Start app
2. Click button Login (this kick off the authentication) => everything works like expected
3. Click button Logout (this kick off the Sign out) ( `PlayGamesPlatform.Instance.SignOut();`)
4. Close the app (real close)
5. Restart the app
6. Click button Login => this time the authentication is also successful, but the callback method of `Authenticate`, has the wrong status flag `false`.

My logcat analyse shows me, that the problem is in relation with the authentication status ERROR_NOT_AUTHORIZED.

Logcat summary (first authentication => everything works like expected):
```
23 20:18:08.699: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:08 +01:00 DEBUG: Activating PlayGamesPlatform.
03-23 20:18:08.706: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:08 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
03-23 20:18:08.716: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:08 +01:00 DEBUG: Creating platform-specific Play Games client.
03-23 20:18:08.734: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:08 +01:00 DEBUG: Creating real IPlayGamesClient
03-23 20:18:09.159: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Entering state: BeforeRoomCreateStartedState
03-23 20:18:09.175: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
03-23 20:18:09.204: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Entering state: ShutdownState
03-23 20:18:09.218: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
03-23 20:18:09.392: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
03-23 20:18:09.445: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
03-23 20:18:09.460: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Populating User
03-23 20:18:09.494: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Found User: [Player: 'xxxx' (id xxxx)]
03-23 20:18:09.496: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Maybe finish for User
03-23 20:18:09.501: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Auth not finished. User=[Player: 'xxxx' (id xxxx)] achievements=
03-23 20:18:09.504: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
03-23 20:18:09.508: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Populating Achievements
03-23 20:18:09.546: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Maybe finish for Achievements
03-23 20:18:09.546: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Auth finished. Proceeding.
03-23 20:18:09.548: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
03-23 20:18:09.747: I/Unity(22159):  [Play Games Plugin DLL] 03/23/15 20:18:09 +01:00 DEBUG: Invoking user callback on game thread
```
Logcat summary (Sign out)
```
03-23 20:19:09.747: I/Unity(24367):  [Play Games Plugin DLL] 03/23/15 21:24:40 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
```

Logcat summary (second authentication => get callback with wrong status):
```
03-23 20:20:24.944: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:24 +01:00 DEBUG: Activating PlayGamesPlatform.
03-23 20:20:24.948: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:24 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
03-23 20:20:24.955: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:24 +01:00 DEBUG: Creating platform-specific Play Games client.
03-23 20:20:24.962: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:24 +01:00 DEBUG: Creating real IPlayGamesClient
03-23 20:20:25.049: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Entering state: BeforeRoomCreateStartedState
03-23 20:20:25.084: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
03-23 20:20:25.096: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Entering state: ShutdownState
03-23 20:20:25.107: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
03-23 20:20:25.110: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
03-23 20:20:25.199: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Invoking user callback on game thread
03-23 20:20:25.271: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: PlayGamesHelperObject.OnApplicationPause True
03-23 20:20:25.324: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus False
03-23 20:20:30.067: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus True
03-23 20:20:30.171: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: PlayGamesHelperObject.OnApplicationPause False
03-23 20:20:30.530: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
03-23 20:20:30.573: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
03-23 20:20:30.587: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Populating User
03-23 20:20:30.635: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Found User: [Player: 'xxxx' (id xxxx)]
03-23 20:20:30.639: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Maybe finish for User
03-23 20:20:30.650: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Auth not finished. User=[Player: 'xxxx' (id xxxx)] achievements=
03-23 20:20:30.662: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
03-23 20:20:30.679: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Populating Achievements
03-23 20:20:30.758: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Maybe finish for Achievements
03-23 20:20:30.762: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Auth finished. Proceeding.
```

**Comment by Laikkae** [comment]
You seem to have the same kind of base issue that is described in #375. As can be found on the log you provided about the second authentication, auth transition is handled twice:

```
03-23 20:20:25.110: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
03-23 20:20:25.199: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:25 +01:00 DEBUG: Invoking user callback on game thread
```
```
03-23 20:20:30.530: I/Unity(22324):  [Play Games Plugin DLL] 03/23/15 20:20:30 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
```

The first, seemly incorrect authentication process fires the callbacks and thus provides the incorrect status flag, even if authentication is successful later on. @readych, do you have saved games enabled by any chance? I'm having this problem only when they are enabled.

**Comment by readych** [comment]
@Laikkae Yes, I have saved games enabled. And you have absolutely right: This problem only appears, if the save game support is enabled (`EnableSavedGames()`).
Further it seems, that my bug report is about the same issue like the bug report #375.

**Comment by CodingStudios** [comment]
I was able to resolve this issue by using PlayGamesPlatform.Instance.Authenticate(OnAuthenticationCallback, false); with a real callback method. If I use the method like in the example it returns before the authentication is actually complete.

**Comment by claywilkinson** [comment]
This is resolved in version 0.9.20 of the plugin. Please reopen an issue if there are still questions.

**Comment by readych** [comment]
It seems that the version 0.9.20 didn't fix the problem. The same issue still exists in the version 0.9.20.
