### ISSUE TITLE
Exclude the pluggin on iOS

### ISSUE THREAD

**Issue by robinDesBits** [playgameservices/play-games-plugin-for-unity#585]
Hello ! 
I have one project for andoid and iOS, but I don't want to use google play game in iOS. So I used NO_GPGS tag in other setting. But it's didn't totally removed the pluggin, since I have an error on xcode; "ios_support.h file not found".

I had also an error "Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(41,39): error CS0117: `UnityEditor.BuildTarget' does not contain a definition for `iOS'" so i changed the line
```
#if UNITY_4_6
 if (target != BuildTarget.iPhone) 
{
      return; 
}
#else
            if (target != BuildTarget.iOS)
            {
                return;
            }
#endif
```

by writting BuildTarger.iPhone on the else. Maybe it's my mistake ? (I have unity 4.3.3)

**Comment by claywilkinson** [comment]
@robinDesBits - thanks for the snippet - I'll update the plugin to check for older versions of Unity (somewhere along the line they changed the constant name).  After you made that change, were you successful in excluding the plugin?

**Comment by robinDesBits** [comment]
I don't think, because I need to add a framework (googleplus framework) and after I have an error with ios_support file not found. But I'm also using admob pluggin, so maybe the problem is from it (https://github.com/googleads/googleads-mobile-plugins/tree/master/unity). But I don't think.

**Comment by robinDesBits** [comment]
Ok I know what is the problem, in your post build it's write:
    string pluginDir = pathToBuiltProject + "/Libraries/Plugins/iOS";

whereas the path Plugins/iOS doesn't exist, all is in Libraries. 
So I have replaced this line by this one, and it seems to work.
    string pluginDir = pathToBuiltProject + "/Libraries/Plugins/iOS";

 I will send this modification to the guy who have the mac (so who is using xcode), and say you if my problem is solve ;)

**Comment by claywilkinson** [comment]
This has been fixed, and 0.9.20 was repackaged to include this fix.  Please download the latest plugin and try it out.  If you have more issues please re-open this issue.  Thanks!

**Comment by ZenithCode** [comment]
I'm using 0.9.21 with NO_GPGS but it still throws missing GooglePlus.h error.

**Comment by claywilkinson** [comment]
@ZenithCode  - which version of Unity?  I think they keep shuffling around the source code location.

**Comment by ZenithCode** [comment]
5.1.2f1

**Comment by ZenithCode** [comment]
The AppController.mm is at Assets/Plugins/iOS/GPGSAppController.mm

**Comment by claywilkinson** [comment]
Where is it ending up in the xcode project? I just tried with 5.1.1 and it worked OK.  GPGSAppController.mm was in Libraries/Plugins/iOS/GPGSAppController.mm.  It was empty.  It looks like for some projects it is ending up in Libraries/GPGSAppController.mm.  Is that where your's is?

**Comment by ZenithCode** [comment]
Ok - your comment helped us resolve the problem.

We were using Perforce and since the file was not checked out, Unity had no
rights to create an empty version of the file.

Problem resolved.
Cheers

On Wednesday, 29 July 2015, Clayton Wilkinson <notifications@github.com>
wrote:

> Where is it ending up in the xcode project? I just tried with 5.1.1 and it
> worked OK. GPGSAppController.mm was in
> Libraries/Plugins/iOS/GPGSAppController.mm. It was empty. It looks like for
> some projects it is ending up in Libraries/GPGSAppController.mm. Is that
> where your's is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/585#issuecomment-126075352>
> .
>


-- 
Anthony Demanuele

**Comment by claywilkinson** [comment]
Sounds good.
