### ISSUE TITLE
LoadScores, callback doesn't get called

### ISSUE THREAD

**Issue by paidgeek** [playgameservices/play-games-plugin-for-unity#711]
Loading scores, as shown at [Accessing Leaderboard data](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#accessing-leaderboard-data), doesn't work. In my current setup, the callback never gets called, but authentication, posting scores and viewing leaderboard/achievement UI works without problems.

I'm using the latest plugin version.

**Comment by Fiurens** [comment]
@paidgeek I am having the same problem, also tried both ways of loading scores, none of them work for me.

**Comment by claywilkinson** [comment]
Can you share a log of when you call LoadScores?

**Comment by paidgeek** [comment]
@claywilkinson 
Using Social.ILeaderboard I get this:
*[Play Games Plugin DLL] {date here} DEBUG: LoadScores,board=GooglePlayGames.PlayGamesLeaderboard callback is System.Action`1[System.Boolean]*
and nothing else.

Using PlayGamesPlatform.LoadScores() there are no logs.

**Comment by claywilkinson** [comment]
OK - I"ll take a look.

**Comment by Fiurens** [comment]
I think mine is a different one, i get the OK from the response, but with no scores.

[Play Games Plugin DLL] 09/18/15 11:45:49 -03:00 DEBUG: Ente
ring internal callback for LeaderboardManager#InternalFetchCallback
[Play Games Plugin DLL] 09/18/15 11:45:49 -03:00 DEBUG: Ente
ring internal callback for LeaderboardManager#InternalFetchSummaryCallback
!!! [Play Games Plugin DLL] 09/18/15 11:45:49 -03:00 WARNING:
 Error returned from fetchScoreSummary: GooglePlayGames.Native.PInvoke.FetchScor
eSummaryResponse
I/Unity   (30499): Setting leaderboard from: [LeaderboardScoreData: mId=CgkI17_o
yuYWEAIQIg,  mStatus=Success, mApproxCount=0, mTitle=Robotoad PvP]

**Comment by claywilkinson** [comment]
I checked this with the SmokeTest sample, and there was a bug in processing the response.  This has been fixed today, so if you download and re-import the plugin it should work.

One other thing to note, is that the permissions the player has configured for sharing game activity will affect the leaderboard.  So social and public could be different (for example, my score shows up on social board, but not the public).

You can call ShowLeaderboardUI() as a way to confirm you are getting the correct data back.

**Comment by paidgeek** [comment]
For me, callback still doesn't execute. I'm interested if it works for you, @Fiurens. I might be doing something wrong. I created new project, followed instructions of setting everything up and still nothing.

**Comment by Fiurens** [comment]
It´s working for me now! But im using PlayGamesPlatform.Instance.LoadScores which returns IScore[]

**Comment by claywilkinson** [comment]
OK to close?

**Comment by claywilkinson** [comment]
Same issue as #731 - which has a workaround...

**Comment by DanielK0926166** [comment]
Hi. I'm using version 0.9.26  and I'm getting the same issue. I see this was fixed in september.
I've tried all ways to get the score, the best result was when I've got:
[Play Games Plugin DLL] {date here} DEBUG: LoadScores,board=GooglePlayGames.PlayGamesLeaderboard callback is System.Action`1[System.Boolean]
Could you help me please? Thank you
