### ISSUE TITLE
iOS: Missing or invalid Resources data. Check that CLIENT_ID is define.

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#719]
Hello, 

I'm getting the Error-Message that the CLIENT_ID is missing, but i thought it is optional? And as I don't want to build a Web App I have no CLIENT_ID or am i mixing up something?

I am running the iOS Setup on a MacBook Pro. 

I have entered the Bundle Identifier, the constans class name and the Resources Definitions from GoogleDevConsole.

Thank you. =)

**Comment by claywilkinson** [comment]
This means that you don't have a linked app that is for iOS.  In the game console, select your game, then Linked Apps, then add an app for iOS.

**Comment by Armend** [comment]
First, thank you for the fast reply. 

I really had forgotten to link an iOS-App, thank you. But anyway, the Error shows again. Is it correct, that there are just 3 input-fields and one input-area? It looks like there should be 4 Input fields: http://prntscr.com/8jprde

**Comment by Armend** [comment]
Could somebody please check if this is true? Do i miss an inputfield?

**Comment by claywilkinson** [comment]
It looks like the heading for the web client id is in there twice, there are no missing input fields.

Once you add the linked iOS app in the console, you can copy the resources for Objective-C into the resource definition edit box.  One of the values in the resource data is the client id.

**Comment by Armend** [comment]
@claywilkinson thank you very much, the bug was caused because i copied the resource data BEFORE linking an iOS-App in the Google Developer Console, so there was no Client ID.

**Comment by claywilkinson** [comment]
Great! I'll mark this as a bug to fix the field captions.

**Comment by yafarida** [comment]
+1

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.26

**Comment by chanbrown007** [comment]
I still get this error? I am brand new to using this and I have no clue what is supposed to go in the Resource field... I haven't touched anything else either. I just opened unity, did the iOS setup and keep getting the CLIENT_ID missing

**Comment by Armend** [comment]
Hey Chanbrown007,

you have to setup your iOS Client in the GoogleDevConsole first: http://fs5.directupload.net/images/160201/ycvp4lwi.png

 THEN you have to copy the ressources you get from the GoogleDevConsole.
http://fs5.directupload.net/images/160201/9soiyqwg.png

Note that you will need the Objectiv-C Version of the ressources. And on top of this ressources there will be your CLIENT_ID. http://fs5.directupload.net/images/160201/s3ypacs6.png

The exact naming of the Links could be different, because I have not the english version of the GoogleDevConsole.
